// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6LLPyFwBzDRimw0qnY9xs3bro5lFQEW0',
    appId: '1:566988380116:web:40ca82d42a8bc9822d2841',
    messagingSenderId: '566988380116',
    projectId: 'todolist-a3f69',
    authDomain: 'todolist-a3f69.firebaseapp.com',
    storageBucket: 'todolist-a3f69.firebasestorage.app',
    measurementId: 'G-D6HRQW5SHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgPrH2qWuWieY7_OpH8wqgX5PriULyXI',
    appId: '1:566988380116:android:f68716ac6d5881f92d2841',
    messagingSenderId: '566988380116',
    projectId: 'todolist-a3f69',
    storageBucket: 'todolist-a3f69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBdE4KtuAI_wr2WqfY8rJthK6ga7Q2Hw',
    appId: '1:566988380116:ios:5fd54568867cf62b2d2841',
    messagingSenderId: '566988380116',
    projectId: 'todolist-a3f69',
    storageBucket: 'todolist-a3f69.firebasestorage.app',
    iosBundleId: 'br.com.marconetenorio.todoList',
  );
}
